version: '2'

networks:
  ros:
    driver: bridge

services:
  ros-master:
    image: ros:indigo-ros-core
    command: stdbuf -o L roscore
    networks:
      - ros
    restart: always

  ros-dev:    
    image: jacknlliu/ros:indigo-ide
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=ros-dev"
      - "QT_X11_NO_MITSHM=1"
      - DISPLAY
    networks:
      - ros
    volumes:
      - ../wanderbot-ws:/home/ros/catkin-ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /home/ros/catkin-ws
    command: terminator
    tty: true
    stdin_open: true