FROM jacknlliu/ros:indigo-ide

RUN apt-get update && \
    apt-get install ros-indigo-turtlebot ros-indigo-turtlebot-apps ros-indigo-turtlebot-interactions ros-indigo-turtlebot-simulator ros-indigo-kobuki-ftdi ros-indigo-rocon-remocon ros-indigo-rocon-qt-library ros-indigo-ar-track-alvar-msgs && \
    apt-get install -y ros-indigo-turtlebot-gazebo ; exit 0